version: '3.4'

services:
    employeecrud_service:
        image: ${DOCKER_REGISTRY-}employeecrudservice
        build:
            context: .
            dockerfile: EmployeeCrud_Service/Dockerfile

    login_service:
        image: ${DOCKER_REGISTRY-}loginservice
        build:
            context: .
            dockerfile: Login_Service/Dockerfile
        ports:
            - "5000:80"

    sql-server-db2 :
        container_name: sql-server-db2
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:                  
            - "1433:1433" 

        environment:
            MSSQL_SA_PASSWORD: "Pa$$_w0rd"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
