version: '3.4'

services:

    login_service:
        image: ${DOCKER_REGISTRY-}loginservice
        build:
            context: .
            dockerfile: Login_Service/Dockerfile
        ports:
            - "5000:80"
        depends_on: 
            - mssql-login-db
        
    employeecrud_service:
        image: ${DOCKER_REGISTRY-}employeecrudservice
        build:
            context: .
            dockerfile: EmployeeCrud_Service/Dockerfile
        ports:
            - "5100:80"
            - "5101:443"

        depends_on: 
            - mssql-employees-db 

    mssql-employees-db :
        container_name: mssql-employees-db 
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:                  
            - "4000:1433" 

        environment:
            MSSQL_SA_PASSWORD: "Pa$$_w0rd"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"

    mssql-login-db :
        container_name: mssql-login-db
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:                  
            - "4001:1433" 

        environment:
            MSSQL_SA_PASSWORD: "Pa$$_w0rd"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
